---
- name: Wait for apt locks to be released
  shell: while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 2; done
  changed_when: false

- name: Force working DNS server inside VM
  shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf
  changed_when: false

- name: Update apt cache and install PostgreSQL
  apt:
    name: 
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is started and enabled
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create system user 'operator'
  user:
    name: operator
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Configure PostgreSQL to listen on all interfaces
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses\s*=\s*.*'
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Allow connections from worker node to PostgreSQL
  postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    databases: all
    users: all
    address: 192.168.150.0/24
    method: md5
  notify: restart postgresql