---
- name: Wait for apt locks to be released
  shell: while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 2; done
  changed_when: false

- name: Force working DNS server inside VM
  shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf
  changed_when: false

- name: Update apt cache and install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure Nginx is started and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Create system user 'teacher' with sudo privileges
  user:
    name: teacher
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Create service user 'app' without home and login
  user:
    name: app
    shell: /usr/sbin/nologin
    create_home: no
    system: yes

- name: Configure Nginx as a reverse proxy
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://127.0.0.1:8080;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
      }
  notify: restart nginx