---
- name: Базове налаштування всіх віртуальних машин
  hosts: all
  become: yes
  roles:
    - common

- name: Розгортання та конфігурація бази даних MariaDB
  hosts: db
  become: yes
  roles:
    - db

- name: Розгортання веб-застосунку та Nginx
  hosts: workers
  become: yes
  roles:
    - worker
